// Generated by CoffeeScript 2.4.1
(function() {
  var app, express, listener;

  express = require("express");

  app = express();

  app.use(express.static("public"));

  // http://expressjs.com/en/starter/basic-routing.html
  app.get('/', function(q, s) {
    return s.sendFile(__dirname + '/views/index.html');
  });

  // listen for requests :)
  listener = app.listen(process.env.PORT, function() {
    return console.log('Your app is listening on port ' + listener.address().port);
  });

}).call(this);
