version: 2
jobs:
  build:
    docker:
      - image: cypress/base:14
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache ## cache both yarn and Cypress!
      - run:
          name: Build
          command: yarn build
      - run:
          name: Start Server
          command: $(yarn bin)/pm2 start server.js
      - run: $(yarn bin)/cypress run --record --key $RECORD_KEY
