// Generated by CoffeeScript 2.4.1
describe('My First Test', function() {
  return it('Checks that the menu bar appears on small screens', function() {
    cy.visit('localhost:3000');
    cy.viewport("iphone-6");
    cy.contains("Xtreme Kleen");
    cy.get(".material-icons").click();
    return cy.get("#mobile-demo > :nth-child(3) > a").should("be.visible");
  });
});
