// Generated by CoffeeScript 2.4.1
describe('My First Test', function() {
  return it('Visits the Kitchen Sink', function() {
    cy.visit('localhost:3000');
    cy.viewport(375, 667);
    cy.contains("Xtreme Kleen");
    cy.get(".material-icons").click();
    return cy.get("#mobile-demo > :nth-child(3) > a").should("be.visible");
  });
});
